export const wuwaData = [
  { id: 'rover-spectro', name: 'Rover Spectro', element: 'Spectro', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'rover-havoc', name: 'Rover Havoc', element: 'Havoc', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'jiyan', name: 'Jiyan', element: 'Aero', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'yinlin', name: 'Yinlin', element: 'Electro', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'calcharo', name: 'Calcharo', element: 'Electro', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'encore', name: 'Encore', element: 'Fusion', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'jianxin', name: 'Jianxin', element: 'Aero', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'lingyang', name: 'Lingyang', element: 'Glacio', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'verina', name: 'Verina', element: 'Spectro', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'jinhsi', name: 'Jinhsi', element: 'Spectro', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'changli', name: 'Changli', element: 'Fusion', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'zhezhi', name: 'Zhezhi', element: 'Glacio', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'xiangli-yao', name: 'Xiangli Yao', element: 'Electro', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'the-shorekeeper', name: 'The Shorekeeper', element: 'Spectro', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'camellya', name: 'Camellya', element: 'Havoc', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'yangyang', name: 'Yangyang', element: 'Aero', weaponType: 'Sword', rarity: 4, image: '' },
  { id: 'chixia', name: 'Chixia', element: 'Fusion', weaponType: 'Pistols', rarity: 4, image: '' },
  { id: 'baizhi', name: 'Baizhi', element: 'Glacio', weaponType: 'Rectifier', rarity: 4, image: '' },
  { id: 'sanhua', name: 'Sanhua', element: 'Glacio', weaponType: 'Sword', rarity: 4, image: '' },
  { id: 'danjin', name: 'Danjin', element: 'Havoc', weaponType: 'Sword', rarity: 4, image: '' },
  { id: 'mortefi', name: 'Mortefi', element: 'Fusion', weaponType: 'Pistols', rarity: 4, image: '' },
  { id: 'aalto', name: 'Aalto', element: 'Aero', weaponType: 'Pistols', rarity: 4, image: '' },
  { id: 'taoqi', name: 'Taoqi', element: 'Havoc', weaponType: 'Broadblade', rarity: 4, image: '' },
  { id: 'yuanwu', name: 'Yuanwu', element: 'Electro', weaponType: 'Gauntlets', rarity: 4, image: '' },
  { id: 'youhu', name: 'Youhu', element: 'Glacio', weaponType: 'Gauntlets', rarity: 4, image: '' },
  { id: 'lumi', name: 'Lumi', element: 'Electro', weaponType: 'Sword', rarity: 4, image: '' },
  { id: 'buling', name: 'Buling', element: 'Electro', weaponType: 'Rectifier', rarity: 4, image: '' },
  { id: 'carlotta', name: 'Carlotta', element: 'Glacio', weaponType: 'Pistols', rarity: 5, image: '' },
  { id: 'roccia', name: 'Roccia', element: 'Havoc', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'phoebe', name: 'Phoebe', element: 'Spectro', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'brant', name: 'Brant', element: 'Fusion', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'cantarella', name: 'Cantarella', element: 'Havoc', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'zani', name: 'Zani', element: 'Spectro', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'ciaccona', name: 'Ciaccona', element: 'Electro', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'augusta', name: 'Augusta', element: 'Glacio', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'iuno', name: 'Iuno', element: 'Spectro', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'galbrena', name: 'Galbrena', element: 'Fusion', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'qiuyuan', name: 'Qiuyuan', element: 'Aero', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'chisa', name: 'Chisa', element: 'Havoc', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'lynae', name: 'Lynae', element: 'Glacio', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'mornye', name: 'Mornye', element: 'Havoc', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'aemeath', name: 'Aemeath', element: 'Fusion', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'luuk-herssen', name: 'Luuk Herssen', element: 'Spectro', weaponType: 'Pistols', rarity: 5, image: '' },
  { id: 'sigrika', name: 'Sigrika', element: 'Aero', weaponType: 'Gauntlets', rarity: 5, image: '' },
  { id: 'hiyuki', name: 'Hiyuki', element: 'Glacio', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'denia', name: 'Denia', element: 'Electro', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'cartethyia', name: 'Cartethyia', element: 'Spectro', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'lupa', name: 'Lupa', element: 'Fusion', weaponType: 'Broadblade', rarity: 5, image: '' },
  { id: 'suisui', name: 'Suisui', element: 'Aero', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'yangyang-xuanling', name: 'Yangyang Xuanling', element: 'Electro', weaponType: 'Sword', rarity: 5, image: '' },
  { id: 'lucy', name: 'Lucy', element: 'Spectro', weaponType: 'Pistols', rarity: 5, image: '' },
  { id: 'rebecca', name: 'Rebecca', element: 'Glacio', weaponType: 'Rectifier', rarity: 5, image: '' },
  { id: 'lucilla', name: 'Lucilla', element: 'Havoc', weaponType: 'Sword', rarity: 5, image: '' }
];
